# ----------- Etapa 1: Construcción -----------
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app

# Copiamos el pom.xml y descargamos dependencias primero (mejora cache)
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiamos el código fuente y construimos el jar
COPY src ./src
RUN mvn clean package -DskipTests

# ----------- Etapa 2: Imagen final -----------
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copiamos el jar desde la etapa anterior
COPY --from=builder /app/target/customers-service-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto del servicio
EXPOSE 5002

# Comando de ejecución
ENTRYPOINT ["java", "-jar", "app.jar"]